### ISSUE TITLE
Reduce footer items

### ISSUE THREAD

**Issue by ujmappa** [StarbeamOne/home#116]
"Powered by Server-side Blazor", "Phantom HTML5 UP Template" and "Proudly Made in Michigan" are not needed in the footer. First two are technical details (they do not open in new tab?!), Michigan is something I would move to the blog.

The build number and build time are informations that would be needed in a troubleshooting page where user can send in an issue, otherwise it's an information that noone needs. 

On the other hand "Terms of use" and "Privacy policy" are very much needed and important for legal issues, and they should be kept in the footer, but also have a place in the menu.

**Comment by Mike-E-angelo** [comment]
Thank you for your feedback.  This is all work from the start of the project.  The Phantom HTML5 Template was a request/requirement from the source provider to use their templates.  Or really, a courtesy.  It is their template which has been heavily modified for my own purposes here, but I still think it is respectful to let others know its origins.

Other information architecture decisions (and opinions :)) are probably best suited for appropriate personnel once I can afford them :D

**Comment by ujmappa** [comment]
Basically you are advertising that your product does not have a unique look :)

**Comment by Mike-E-angelo** [comment]
I'd rather think people prefer honesty than not. :D

**Comment by ujmappa** [comment]
Okay, let me honestly write the first thing that came to my mind when reading this: you could also write there the size of your cock. It would be honest, still, it's kind of an information you might keep for yourself...

**Comment by Mike-E-angelo** [comment]
I amend my statement to reflect *appropriate* honesty. 😘

To be clear here you are suggesting that I hide the fact that I used a template from a site whose requested suggestion for using said template was/is to make mention of the source of the originating content, i.e. link exchange.

**Comment by ujmappa** [comment]
At first place I am saying that this information does not belong on the footer. You can create a page for that info (like an impressum). On second place, I do not see a link to starbeam.one on the page of the template, so it is not a link exchange. First you speak about honesty, now link exchange.. I guess I cannot move you to professional direction, can I?

**Comment by Mike-E-angelo** [comment]
Indeed link exchange is not entirely accurate as it is one way, more like the spirit of one. I do think it's better to be honest more than not upfront.  Especially when technically competing with fields (crypto) which seems to be anything but.  If you did read their terms you should find that they requested a mention back to them (at least that is how I found it), and considering the amount of work they saved me up front I think the footer is plenty OK to show the love for a v0 product. 👍

**Comment by ujmappa** [comment]
They do not request it. And how long do you plan to stay at v0? Will you move it in v1?

**Comment by Mike-E-angelo** [comment]
> They do not request it

I did now just check them out and it is indeed much different than I remember it.  It was very clear/suggested to provide a link back to them, or maybe that was my impression.  It was four years ago, after all.  I was easily impressed back then what can I say. 😆

> Will you move it in v1?

When I can afford it :)

I should also say I am thinking in terms of the UX being v0 currently.  We're aiming for the site v1 in April, but it will feature the current UX which I consider v0 and a placeholder until the calvary arrives.

**Comment by ujmappa** [comment]
Okay, then back that I said previously: you are advertising that this an amateur site with a non-unique design.
Pretty lame self-marketing when you ask me.. ;)

**Comment by Mike-E-angelo** [comment]
I appreciate that you're trying to improve the application, but calling someone or their efforts lame is simply not constructive.

**Comment by ujmappa** [comment]
Giving up on this as well.

**Comment by Mike-E-angelo** [comment]
FWIW: https://html5up.net/license

![image](https://github.com/StarbeamOne/home/assets/2931376/58df780f-912f-4a7d-8cba-1af4678a24c3)

**Comment by Mike-E-angelo** [comment]
Please note that I have removed the Blazor / HTML5UP / Michigan reference from the footer.  There are references to these in the [About / Acknowledgements](https://starbeam.one/about/acknowledgements) and it's probably better to be subtle about it than not.  I added a reference to HTML5UP there to ensure compliance with the above.

**Comment by ujmappa** [comment]
It's okay to have these informations, they just don't belong to the footer. Let's keep things not distracting and clean.
Now only the build number and build time remains to be removed.

**Comment by Mike-E-angelo** [comment]
> Now only the build number and build time remains to be removed.

I use these constantly and think they are/look cool. :)  I have also seen other sites do this which is where I got the inspiration.

**Comment by ujmappa** [comment]
Okay, maybe later you make up your mind, users do not need it
