### ISSUE TITLE
Improve Menu/Navigation Experience

### ISSUE THREAD

**Issue by ujmappa** [StarbeamOne/home#119]
- [x] Welcome is not needed, you click on starbeam.one, and there you are
- [x] Help should go down in footer (the icon in the header is also not needed)
- [x] Every item of Information can go to the footer
- [x] Except support, that should be a simple mailto in the footer. Users do understand the chat icon. Discord invitation should be in the footer at follow section (I guess it is already there, never clicked it) 
- [x] The catalogs of the users can be at one page with tabs of artists, collectors, all users, there is no need for 3 menu items
- [x] The markets.. well.. I already issued something about having one market... you could start with one market page that offers a choice on the top of the page filtering for the current ones, this way it can become one menu point as well, this will also result quicker switch between markets
- [x] Definitions, new inventory, existing inventory should be also one menu entry. Currently they are on a same page, which is great
- [x] Identities should not be in the menu, but on the user profile
- [x] Assets should be removed from the menu, and even the page should not exist. This is a technical details that you create assets for inventory items. Also unused assets should be checked every day and deleted automaticaly if they are not linked. This way you get some space back. I know it's a bit rough, but believe me, people don't care about these.
- [x] Add notifications to the menu. If deposit, withdraw and user account can get a menu item, this can as well. Starvault also deserves a place here.

**Comment by Mike-E-angelo** [comment]
>  Except support, that should be a simple mailto in the footer. Users do understand the chat icon. Discord invitation should be in the footer at follow section (I guess it is already there, never clicked it)

The support page outlines all of this.  There is a button to email support there.  It seems like you are suggesting the Discord but then correctly denote that it's already there.  It is unclear the ask here.

> Identities should not be in the menu, but on the user profile

Note that this is the Sales Profile which does not exist until you promote your profile to do so.  Identities are already listed there.

Changes above are deployed in staging:

https://staging.starbeam.one/

You may need to sign in and promote your profile to test the Sales Profile functionality above.  This uses a different database than production.

> Also unused assets should be checked every day and deleted automaticaly if they are not linked. This way you get some space back

Captured in #63

**Comment by ujmappa** [comment]
Hmm.. It's not exactly what I proposed..  The first and foremost error is, that I am not able to issue an inventory.

Inventroy:
- Add one menu point for inventory/definition page

Market:
- There should not be a middle page
- Proposing two menu points: sale and resale listings
- Both can be filtered for standard, featured and traditional
- Include most wanted somehow.. maybe a button, but an order by would be the best

Catalogs:
- There should not be a middle page
- Proposing two menu points: license and user explorer
- User explorer should have filter/tabs/buttons to show artists, collectors or all users

Account:
- Maybe it should be renamed, as it is about my flares
- Deposit and withdraw can come here with a button
- Deposit and withdraw will not needed in the menu
- StarVault link can be removed from here (instead add history without a button?)

What is okay:
- Capacity (Ungroup)
- Customers (Ungroup)
- Notifications (Ungroup)
- StarVault (Ungroup)

Ungroup (no groups are needed, not even for user):
- There is no need for User group, instead just put Profile in the menu and ungroup what's under it
- If you think that menu entries should be divided into groups somehow, use a divider

**Comment by ujmappa** [comment]
Also why are new footer elements put in a new line?

**Comment by ujmappa** [comment]
In footer "Get Help" should be renamed to "Support". I still don't think it needs a standalone page, but at least let's keep the name professional. Order footer elements by their importance. Those which open a new tab should be last.

**Comment by ujmappa** [comment]
Menu does not need header: "MENU". We know it's that :) You could put there my username instead.

**Comment by Mike-E-angelo** [comment]
I am having a little difficulty with what you mean by ungroup, can you please elaborate?

**Comment by Mike-E-angelo** [comment]
Note that we had one member already request deposit/withdraw on the menu as it was not clear where to do this.  I suggest stating `Account (Deposit / Withdraw)` as the line item in this case.

**Comment by Mike-E-angelo** [comment]
![image](https://github.com/StarbeamOne/home/assets/2931376/500be8e4-2775-4c38-9c7d-462cc334641f)

**Comment by Mike-E-angelo** [comment]
No more scrolling in desktop I likey

![image](https://github.com/StarbeamOne/home/assets/2931376/03ed2b73-a93b-4dbc-ae1c-7b170e5cc43d)

**Comment by Mike-E-angelo** [comment]
I like the middle page link as otherwise it will be a title just sitting there.  Linking to a middle page adds more value for those who try to press the title. :)

**Comment by ujmappa** [comment]
Sign out should be definetely at the bottom. But yes, the main idea is not to scroll much, not even on Mobile

**Comment by ujmappa** [comment]
> I am having a little difficulty with what you mean by ungroup, can you please elaborate?

Well, I had the idea to remove group titles, like "Catalogs", "Markets", etc. but looking at your screenshot they look good now that it's more compact.

**Comment by Mike-E-angelo** [comment]
I agree with moving Sign Out to bottom but people might not realize you can scroll and might get confused/frustrated on how to sign out 🤔

**Comment by ujmappa** [comment]
Come on, they realized it until now :) Just put sign out to the bottom of the menu.

**Comment by ujmappa** [comment]
> Note that we had one member already request deposit/withdraw on the menu as it was not clear where to do this. I suggest stating `Account (Deposit / Withdraw)` as the line item in this case.

Manage flares? Balance? Credits? StarWallet? :) Anything, but no long descriptions and brackets. Even simple account is better, however for me account would mean manage profile

**Comment by Mike-E-angelo** [comment]
> Come on, they realized it until now :) Just put sign out to the bottom of the menu.

I've actually had one report where they could not find it, which is why I mention it.  However, they felt silly they didn't see it before I mentioned how to find it.  I am guessing you are correct, however, with the new lightweight menu. :)

> Manage flares? 

Winner 👍

**Comment by Mike-E-angelo** [comment]
Latest version deployed to staging 👍

**Comment by ujmappa** [comment]
I do not think that the divider hr element is needed above the user account. Everything else is okay. Maybe license explorer and users could be aligned.. Explore users, explore licenses.. License explorer, Explore users.. Idk. Leaving this to you. Can go to prod.

**Comment by Mike-E-angelo** [comment]
`<hr />` is such a callback from when I started learning HTML, so had it in there mostly for sentimental reasons as it was a part of the original template.  Removing it does clean it up.  I have made normalized Catalog entries to be `Users` and `Licenses` to match the one-word entries of the other items.  Deployed to production. 👍

**Comment by ujmappa** [comment]
Closing issue, nice work

**Comment by Mike-E-angelo** [comment]
🙏🙏🙏
