### ISSUE TITLE
Reduce menu items 2

### ISSUE THREAD

**Issue by ujmappa** [StarbeamOne/home#120]
- The catalogs of the users can be at one page with tabs of artists, collectors, all users, there is no need for 3 menu items
- The markets.. well.. I already issued something about having one market... you could start with one market page that offers a choice on the top of the page filtering for the current ones, this way it can become one menu point as well, this will also result quicker switch between markets
- Definitions, new inventory, existing inventory should be also one menu entry. Currently they are on a same page, which is great
- Identities should not be in the menu, but on the user profile
- Assets should be removed from the menu, and even the page should not exist. This is a technical details that you create assets for inventory items. Also unused assets should be checked every day and deleted automaticaly if they are not linked. This way you get some space back. I know it's a bit rough, but believe me, people don't care about these.
- Add notifications to the menu. If deposit, withdraw and user account can get a menu item, this can as well. Starvault also deserves a place here.

After all being done you will not need any menu headers anymore as it will be a lot smaller and tighter. Maybe just some dividers, but I do not see the point.

**Comment by Mike-E-angelo** [comment]
Let's please keep similar tasks combined into one issue here on GitHub.  These should be tasks for #119.  I will edit.

**Comment by ujmappa** [comment]
As these also contain page changes, I wanted it separate. One effects the footer, these are more like page consolidations, so the work is different.
