### ISSUE TITLE
Minor change in header icons

### ISSUE THREAD

**Issue by ujmappa** [StarbeamOne/home#121]
User icon is not really needed, people do not change/check much theirselves. There is also no need to display the count in Starvault, count of market is also not displayed, and it is okay this way. I would also set their height to 20-24px in css (for me everything is too big on the site), but that is up to you.

**Comment by Mike-E-angelo** [comment]
I use the profile icon all the time to log in.  Once logging in if the user is not displayed it may be disorienting, especially for new users who may want to get situated.  As for sizes, when providing feedback please denote desktop/tablet/phone for better context. :)

**Comment by ujmappa** [comment]
I guess you pointed out one other change here, change login from icon to somehing more descriptive, like a button for login...

**Comment by Mike-E-angelo** [comment]
It's sort of functional in its approach and is intended.  "Getting to your profile" is a goal whereas "login" is an activity, if that makes sense.  Additionally, if any change is made it will impact existing documentation/screenshots.  We can start labeling for future backlog when we have someone with the bandwidth to address it.

**Comment by ujmappa** [comment]
Okay, it's not that important, maybe for mobile optimization. Starvault count can be removed currently.

**Comment by Mike-E-angelo** [comment]
I am actually in agreement with this as I have 730 items and it's starting to look a bit unwieldy :D  Additionally, it will save a database hit for that number whenever updated.

**Comment by Mike-E-angelo** [comment]
This has been deployed to production.  Please comment with any further feedback/issues and I will further investigate. 👍
