### ISSUE TITLE
Social Media Announcement Integration

### ISSUE THREAD

**Issue by crystalwizard** [StarbeamOne/home#13]
from our discord discussion

might be better if it just let  you artists  post to starebeam one, then sent that post out to all the social media sites, and ran all the mechanics of minting nfts under the covers 
the hardest rule to follow is don't make it easy for your users to leave your website
and that, btw, will set you apart from every other site out there. no one does that
one other suggestion on the automatic stuff - when it sends out to all the social media sites, have it send to the starbeamone account - that way you can send it everwhere, not just to where the user has accounts, and in the post have it list the artist, a link to their starbeamone portfolio, etc. You might also have a second set up that allows them to pick their ow social media accounts and then it would also post out to those accounts as them

**Comment by Mike-E-angelo** [comment]
From discord: https://discord.com/channels/1017361648509517894/1017361648991871010/1034529653358084166

> when it sends out to all the social media sites, have it send to the starbeamone account - that way you can send it everwhere, not just to where the user has accounts, and in the post have it list the artist, a link to their starbeamone portfolio, etc. You might also have a second set up that allows them to pick their ow social media accounts and then it would also post out to those accounts as them

**Comment by Mike-E-angelo** [comment]
Hi @crystalwizard can you explain how this is different from our current announcements which are posted with each issuance and sale?

Examples:
https://twitter.com/StarbeamOne/status/1584993425958600728
https://twitter.com/StarbeamOne/status/1584971002253086734

**Comment by Mike-E-angelo** [comment]
I believe this is implemented now.  We have four events that are monitored:

- Issuances
- Sales
- Listings
- Resales

Whenever these occur we fire off announcements to:

- Twitter
- Facebook
- Instagram
- LinkedIn
- Pinterest
- Reddit
- Discord

If there is something misunderstood/missing please leave a comment and we will discuss further.  Closing for now.
