### ISSUE TITLE
Move Sold Out Items to the Back of the Line

### ISSUE THREAD

**Issue by crystalwizard** [StarbeamOne/home#14]
We want to have some way of filtering out sold out items because they are pushing available items out of visibility.

There should be a toggle button that displays sold-out items and hide them.

---
Original ticket:

impliment something that will move items that are still for sale in front of items that are sold out

possibly also impliment a way for users to put certain items on sale for a short period of time and have them automatically put back to full price

**Comment by Mike-E-angelo** [comment]
@crystalwizard had it right first.  We now move sold-out issuances to the back of the line, and display the available ones first.  This is simpler and does not involve a toggle.  This will be available in the deployment tomorrow

**Comment by Mike-E-angelo** [comment]
This is now deployed to production.  Thank you for feedback and interest in starbeam.one!
