### ISSUE TITLE
Surface File Details in Product Storefront

### ISSUE THREAD

**Issue by Mike-E-angelo** [StarbeamOne/home#70]
We currently process files and grab their details: dimensions, file size, length of time (audio/video), etc.  However, we do not surface the details in the product storefront.

Part of it is paranoid fear on my side about the product storefront SQL query which is quite expensive and one of the most intensive queries because it is so common and used so  much throughout the site.  It is cached per product every 24 hours at the moment.  There are a large amount of joins and adding any more makes me nervous.

That stated it is unknown just how much overhead this will add and some effort should be made to see what the performance impact is.  We're storing the data after all, why not display it?

**Comment by Mike-E-angelo** [comment]
A quick note about file dimensions as currently seen on the product storefront.

We have 3 versions of every file saved:

1. Default This is the file in its original form (no resize)
2. Thumbnail - resized to 320px on its dominant axis (so if the asset is 800px width x 600px height, it would be resized to 320px wide and 240px high) - This is used for social media and front page grid images
3. Preview - resized to 640px on its dominant axis -- used for watermarks and primary image on the storefront.

**Comment by Mike-E-angelo** [comment]
@greenbrook any chance we can get a preview of what this may look like? :D

**Comment by greenbrook** [comment]
So, Mike, it seems to me I got it wrong when I read it for the first time. Did you mean an image display like this (from Behance)? Or did you simply mean the product details (size, format) that are already added by you to the License panel? 

<img width="1049" alt="Знімок екрана 2023-03-02 о 21 28 50" src="https://user-images.githubusercontent.com/125400168/222533379-88479e1e-1aed-4fbc-aab9-8aebfa1c1f0f.png">

**Comment by Mike-E-angelo** [comment]
Whoops!  Disregard this one @greenbrook.  This one's been completed. :)

From: https://alpha.starbeam.one/market/products/45c280d4-6621-4484-61f2-08db1b4b9897
![image](https://user-images.githubusercontent.com/2931376/222535316-aa982f81-6677-48cc-b5fa-7924d5a423ec.png)
