### ISSUE TITLE
Darken the buttons to improve accessibility

### ISSUE THREAD

**Issue by greenbrook** [StarbeamOne/home#80]
I applied Starbeam's standard dark blue #094074 to the filters, to make them noticeable and pronounced. Also, I added a border-radius 10px (in Figma), to give it a more "friendly" look. These decisions are made for adding contrast and accessibility to the design and providing a more modern style. 

![Frame 17](https://user-images.githubusercontent.com/125400168/223736605-30c441bf-a0fe-46c9-a2ef-37b851b792ba.png)

**Comment by Mike-E-angelo** [comment]
Somehow I missed this issue not getting created.  Looking into this now.

**Comment by greenbrook** [comment]
Aw, is it implied?? Amazing! We'll see if the users like it :D

<img width="1292" alt="Знімок екрана 2023-03-10 о 16 20 37" src="https://user-images.githubusercontent.com/125400168/224339832-39dff84d-e22f-4a3d-827e-67f6fe84c059.png">

**Comment by Mike-E-angelo** [comment]
You betcha!  I got that applied and deployed.  Thank you for your valuable input and suggestions. If you have quick wins like these please let me know and I will look into it for you. 👍  Closing this issue for now.
