### ISSUE TITLE
Interface: Toggle Between Product Tiles and Grid

### ISSUE THREAD

**Issue by Mike-E-angelo** [StarbeamOne/home#86]
We need to have a way to toggle between the product grids (current) and the old grid for searching/filtering capabilities.  @greenbrook can you think of something cool here? :)

**Comment by greenbrook** [comment]
A literal toggle? 

![Component 1](https://user-images.githubusercontent.com/125400168/226118511-52959269-73fb-4496-9c9d-848fe46f73f5.png)

**Comment by Mike-E-angelo** [comment]
I was thinking of one state bing "tiles" (current/default) and the other being "grid"... my biggest problem is where to put it.

**Comment by greenbrook** [comment]
Let's start somewhere.

![Frame 37](https://user-images.githubusercontent.com/125400168/226135259-777ad70a-3fac-41c1-914a-58e98dd17bc7.png)

**Comment by greenbrook** [comment]
House told that the simplest idea is often the right one.

![Frame 38](https://user-images.githubusercontent.com/125400168/226135813-279bb0b8-a3e2-46f2-a942-c1ac76dd4223.png)

**Comment by Mike-E-angelo** [comment]
How does that look on mobile? :)

And sorry House, it's simpler than that.  This actually isn't for the front page, primarily, as that works OK with tiles.  This is for the [Product Storefront Explorer](https://alpha.starbeam.one/market/products) and StarVault™, thinking this area here:

![image](https://user-images.githubusercontent.com/2931376/226136069-819f0ff6-0796-4be2-a011-0eb1b9d87ea7.png)

**Comment by greenbrook** [comment]
Ok ) It's really a bit tricky as the eye is fully directed to the left side. The glance slips down from the top to the product display. The artifact on the right side can look "hanging" there. It will be on the left for mobile. Btw, nice point, it's more productive to think of mobile first.

**Comment by greenbrook** [comment]
So, Mike, maybe you're really dreaming of an actual toggle? :D It needs JS, right? Making it fancy just to show that we can :D

**Comment by greenbrook** [comment]
<img width="384" alt="Знімок екрана 2023-03-18 о 22 36 12" src="https://user-images.githubusercontent.com/125400168/226137523-6d6f2cc2-5919-4181-96ab-e0a06c0dab12.png">

I knew that you won't like it but I had to try it :D

**Comment by Mike-E-angelo** [comment]
> maybe you're really dreaming of an actual toggle

yes maybe the same toggle we use for Simple Mode?

![image](https://user-images.githubusercontent.com/2931376/226141624-a83cfe88-f757-48b9-9d00-4187840bf3f3.png)

**Comment by greenbrook** [comment]
Very pretty toggle! Matches the palette!
Would you like to put it under the chips, just above the products?
Where is this toggle? Can't find it on the site.

**Comment by Mike-E-angelo** [comment]
> Would you like to put it under the chips, just above the products?

I was thinking in the[ big red rectangle here](https://github.com/StarbeamOne/home/issues/86#issuecomment-1474978525). :)

> Where is this toggle? Can't find it on the site.

It's in the create/edit definition screen.  You have to have a [promoted artist's account](https://starbeam-one.gitbook.io/home/artists/quick-start/promote-your-profile) to see it.  👍

**Comment by Mike-E-angelo** [comment]
Currently in staging @greenbrook what do you think? 🤔
https://staging.starbeam.one/market/products

**Comment by Mike-E-angelo** [comment]
Deployed
