### ISSUE TITLE
Improve Documentation Visibility

### ISSUE THREAD

**Issue by Mike-E-angelo** [StarbeamOne/home#93]
We want to make documentation easier to find:
- Better Icon: https://github.com/StarbeamOne/home/issues/85#issuecomment-1510273626
- Change Welcome Navigation to include `Wiki`

**Comment by greenbrook** [comment]
New SVG Information icon:

![Info](https://user-images.githubusercontent.com/125400168/232298942-b767ee61-959b-4659-8d2d-1c4aaad9a04d.svg)

**Comment by Mike-E-angelo** [comment]
Deployed
