### ISSUE TITLE
Fancy Purchase Button

### ISSUE THREAD

**Issue by Mike-E-angelo** [StarbeamOne/home#94]
We want to make the purchase button POP!

Visually, not literally 😁

https://twitter.com/EZeleniuk/status/1648269058150739970

**Comment by greenbrook** [comment]
#E15304

![See artwork](https://user-images.githubusercontent.com/125400168/232775582-e0273570-12b2-4455-8043-b769e8a000c6.png)

**Comment by greenbrook** [comment]
#FF6F16

![See artwork](https://user-images.githubusercontent.com/125400168/232775943-99d8e380-70a4-4a0a-bd11-a0bf9395d7ab.png)

**Comment by Mike-E-angelo** [comment]
@greenbrook  `#FF6F16` has been deployed check it out :)

**Comment by Mike-E-angelo** [comment]
although I made that the primary color for all buttons 🤔  looks kinda cool to me

**Comment by Mike-E-angelo** [comment]
This is done and rocking now :D
